version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            # pip install packages/regression_model
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            ls /home/circleci/project/packages/regression_model/regression_model/datasets/
            unzip house-prices-advanced-regression-techniques.zip
            cd packages/regression_model
            py.test -vv tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
